import { RAW_REGIONS } from '@/entities/region';
import type { Application } from './types';

function region(dong: string) {
  return RAW_REGIONS.find((r) => r.dong === dong) ?? null;
}

export const SEED_APPLICATIONS: Application[] = [
  {
    id: 'a-1',
    platform: 'wanted',
    company: '토스',
    region: region('역삼동'),
    position: '프론트엔드 엔지니어 (신입)',
    appliedAt: '2026-08-11',
    viewed: true,
    viewedAt: '2026-08-12',
    postingStatus: '진행중',
    applyStatus: '서류합격',
    link: 'https://www.wanted.co.kr/wd/000000',
    memo: '1차 면접 8/28 14:00, 사전 과제 있음.',
    updatedAt: '2026-08-20'
  },
  {
    id: 'a-2',
    platform: 'jobkorea',
    company: '한화시스템',
    region: region('불당동'),
    position: '소프트웨어 개발 (마이스터고 채용)',
    appliedAt: '2026-08-06',
    viewed: true,
    viewedAt: '2026-08-07',
    postingStatus: '접수마감',
    applyStatus: '서류탈락',
    link: 'https://www.jobkorea.co.kr/Recruit/GI_Read/000000',
    memo: '내년 상반기 재지원 예정.',
    updatedAt: '2026-08-18'
  },
  {
    id: 'a-3',
    platform: 'rallit',
    company: '뤼튼테크놀로지스',
    region: region('삼평동'),
    position: '웹 프론트엔드 인턴',
    appliedAt: '2026-08-18',
    viewed: false,
    viewedAt: null,
    postingStatus: '상시',
    applyStatus: '지원완료',
    link: 'https://www.rallit.com/positions/000000',
    memo: '포트폴리오 v3 제출.',
    updatedAt: '2026-08-18'
  },
  {
    id: 'a-4',
    platform: 'etc',
    company: '대덕전자',
    region: region('관평동'),
    position: '임베디드 SW (학교 추천)',
    appliedAt: '2026-08-14',
    viewed: true,
    viewedAt: '2026-08-14',
    postingStatus: '진행중',
    applyStatus: '최종합격',
    link: 'https://recruit.example.co.kr/notice/12',
    memo: '취업지원부 김선생님 추천. 처우 협의 남음.',
    updatedAt: '2026-08-22'
  },
  {
    id: 'a-5',
    platform: 'wanted',
    company: '뱅크샐러드',
    region: region('여의도동'),
    position: 'QA 엔지니어',
    appliedAt: '2026-08-19',
    viewed: false,
    viewedAt: null,
    postingStatus: '진행중',
    applyStatus: '지원완료',
    link: 'https://www.wanted.co.kr/wd/111111',
    memo: '',
    updatedAt: '2026-08-19'
  },
  {
    id: 'a-6',
    platform: 'jobkorea',
    company: '지니언스',
    region: region('상남동'),
    position: '보안 솔루션 개발',
    appliedAt: '2026-07-30',
    viewed: true,
    viewedAt: '2026-08-02',
    postingStatus: '접수마감',
    applyStatus: '최종불합격',
    link: 'https://www.jobkorea.co.kr/Recruit/GI_Read/222222',
    memo: '2차 면접까지 진행. 네트워크 질문 보완 필요.',
    updatedAt: '2026-08-16'
  },
  {
    id: 'a-7',
    platform: 'rallit',
    company: '오늘의집',
    region: region('서초동'),
    position: '프론트엔드 (주니어)',
    appliedAt: '2026-08-21',
    viewed: true,
    viewedAt: '2026-08-22',
    postingStatus: '상시',
    applyStatus: '지원완료',
    link: 'https://www.rallit.com/positions/333333',
    memo: '',
    updatedAt: '2026-08-22'
  },
  {
    id: 'a-8',
    platform: 'etc',
    company: '카카오엔터프라이즈',
    region: region('도담동'),
    position: '클라우드 엔지니어 (자사 홈페이지)',
    appliedAt: '2026-08-04',
    viewed: false,
    viewedAt: null,
    postingStatus: '접수마감',
    applyStatus: '서류탈락',
    link: 'https://careers.example.com/jobs/9',
    memo: '',
    updatedAt: '2026-08-10'
  },
  {
    id: 'a-9',
    platform: 'wanted',
    company: '리디',
    region: region('삼성동'),
    position: '웹 프론트엔드',
    appliedAt: '2026-08-08',
    viewed: true,
    viewedAt: '2026-08-09',
    postingStatus: '접수마감',
    applyStatus: '서류탈락',
    link: 'https://www.wanted.co.kr/wd/444444',
    memo: '',
    updatedAt: '2026-08-12'
  },
  {
    id: 'a-10',
    platform: 'jobkorea',
    company: '이엠코리아',
    region: region('가경동'),
    position: '제어 SW 개발',
    appliedAt: '2026-07-28',
    viewed: false,
    viewedAt: null,
    postingStatus: '접수마감',
    applyStatus: '서류탈락',
    link: 'https://www.jobkorea.co.kr/Recruit/GI_Read/555555',
    memo: '',
    updatedAt: '2026-08-02'
  },
  {
    id: 'a-11',
    platform: 'etc',
    company: '한국항공우주산업',
    region: region('상남동'),
    position: '항공전자 SW (학교 추천)',
    appliedAt: '2026-08-25',
    viewed: false,
    viewedAt: null,
    postingStatus: '진행중',
    applyStatus: '지원완료',
    link: 'https://recruit.koreaaero.example/jobs/3',
    memo: '학교 추천 마감 8/29',
    updatedAt: '2026-08-25'
  },
  {
    id: 'a-12',
    platform: 'rallit',
    company: '스푼라디오',
    region: region('논현동'),
    position: '주니어 백엔드',
    appliedAt: '2026-08-23',
    viewed: true,
    viewedAt: '2026-08-24',
    postingStatus: '상시',
    applyStatus: '지원완료',
    link: 'https://www.rallit.com/positions/666666',
    memo: '',
    updatedAt: '2026-08-24'
  }
];
